### ISSUE TITLE
[Bug] 3rd Party App Updates Hanging on Install

### ISSUE THREAD

**Issue by gmanc2** [altstoreio/AltStore#1074] opened 2022-10-22 22:40 UTC
I have a developer account, and this is a recent issue. I'm not sure whats causing it, but I tried to reinstall altstore and it worked fine I can even refresh fine, but when I try to install UYou+ it hangs right at the very end. I'm not sure if this is an altserver/altstore issue or its an issue with the UYou+ app, but I have no way of telling as no errors are produced it just hangs. Please let me know if there is something I can do to fix this?

**Comment by gmanc2** [comment] 2022-10-23 00:10
Update: I deleted it and was able to install it on Sideloady. It might be an issue with altstore/server. I tried both the beta and non beta versions of altserver/store.

**Comment by dmdx86** [comment] 2022-10-29 13:59
Yeah, it’s been a problem since iOS 16.0. No acknowledgement from the devs.

Also talked about here: https://github.com/rileytestut/AltStore/issues/1057

**Comment by tillyadam** [comment] 2022-10-29 14:05
I had the same issue, deleted everything multiple times, I tried installing altstore and UYou+ from different computers. After 4-5 remove and reinstall everything, I succesfully installed UYou+ and now it works fine. No idea what the problem could be.

**Comment by Flyingturtle215** [comment] 2022-12-01 03:54
I had the same issue for another app. I deleted Altstore, and it now gets stuck at "Installing Altstore to iPhone" whenever I try to reinstall it.

**Comment by shanegillio** [comment] 2023-01-11 16:50
hey all! sorry for the lack of communication. I'm working on going through our list of reports, and will look into this soon. I have heard there are several issues with some of the youtube appssince iOS 16. I think many of the sources/IPAs were not able to be used anymore. There's a pinned post on the subreddit with mention of a source that should work. If you've tried that one already and it is still failing, let me know

**Comment by gmanc2** [comment] 2023-01-17 02:32
@shanegillio Could you link to the post you're talking about?

**Comment by shanegillio** [comment] 2023-01-19 16:37
looks like they moved the page, but one of the sources at the bottom likely contains the right IPA. all is to say that you should try alternate sources

**Comment by gmanc2** [comment] 2023-01-19 21:34
> looks like they moved the page, but one of the sources at the bottom likely contains the right IPA. all is to say that you should try alternate sources

I get the IPA directly from https://github.com/qnblackcat/uYouPlus/releases, the developer of uYou+. Do you believe that the developer could fix the issue? What is the cause of the issue?

**Comment by shanegillio** [comment] 2023-01-23 16:51
Will look into this further, but hard to say what the exact issue is in this scenario. Will have to do some testing to see if it is in fact an AltStore or uYou+ issue

**Comment by jasonhe54** [comment] 2023-02-05 00:22
> Will look into this further, but hard to say what the exact issue is in this scenario. Will have to do some testing to see if it is in fact an AltStore or uYou+ issue

Just want to add on, Sideloadly seems to do just fine installing it. Signing takes longer than usual, but that's expected given the app size, but nowhere near as long as Altstore (that is to say, it actually succeeds and doesn't hang at the end). As for Altstore, it's hanging near the very very end of the progress bar, and it seems to "revoke" the Developer certificate. The certificate technically isn't "revoked", just that the device no longer recognizes it and thus prevents the app from opening, needing me to reinstall Altstore from Altserver, and then re-sign the apps that are sideloaded. However, the certificate isn't gone from the device as any apps from Altstore that were "revoked" are still counting towards the 3 free app limit.

**Comment by gmanc2** [comment] 2023-02-05 22:17
One last thing, the only reason why I do not use a different developer of uYou+ is because of the features included in his. Also, the issue is fixable, if you delete the current version of the app and reinstall AltStore and then install the IPA. However, I can not do this due to google making Youtube not accept sign-in requests from modified apps. However, when I update the app with AltStore(When it works), I do not have that problem since it keeps me signed in. I really appreciate what you're doing, and thank you for your time! @shanegillio

**Comment by shanegillio** [comment] 2023-02-06 20:48
I see - if the issue is fixed with reinstallation, it tells me that AltStore may think that the app is unavailable? I just spoke with someone on discord with a similar issue. They noted that the apps they had installed were still linked to their AppleID and they needed to remove them before they can refresh/install apps. AltStore was hanging on install because it was unable to properly communicate the error.

**Comment by jasonhe54** [comment] 2023-02-06 23:46
> I see - if the issue is fixed with reinstallation, it tells me that AltStore may think that the app is unavailable?  

Potentially? All I know is that whenever it fails (or hangs) the developer certificate gets "revoked" and just says AltStore is not available and you need to reinstall it with a computer, even though that's very clearly not the case. Sideloading with another service (using the same free dev account) causes issues like the 3-app limit was hit. So, iOS knows there's 3 apps already signed and installed, but it doesn't show up under the profiles section in Settings, nor can you open it. 

>They noted that the apps they had installed were still linked to their AppleID and they needed to remove them before they can refresh/install apps.

Yep, that might be a better way to describe it. The apps were still "linked" to my Apple ID, just not showing up under Settings and unable to open. I did not have to remove them before reinstalling. I reinstalled AltStore from my laptop, that signed AltStore, then used AltStore to refresh uYou+ with I had install and that worked. However, I was unable to get AltStore to update uYou+, the same issue occurred each time.

**Comment by shanegillio** [comment] 2023-02-07 20:59
Would you mind telling me exactly how you are attempting to update uYou+. I just did some testing myself, and noticed that the most recent release of the app on GitHub works. However, it also tells me there is a newer version available? Then when I try to update, that has issues leading to the app crashing. If I ignore the update pop-up and just use the app it's fine. 

I am doing all this on my phone in AltStore and not using AltServer to sideload directly or update.

**Comment by jasonhe54** [comment] 2023-02-08 02:38
> Would you mind telling me exactly how you are attempting to update uYou+.

I have an older version already installed but basically grab the latest IPA, don't delete the old version otherwise signing in gets annoying. Then go into Altstore, press the plus, select the IPA for uYou+, then theoretically it should work, but for me it doesn't. 

>However, it also tells me there is a newer version available?

I noticed that too but I'm unsure why. I managed to sideload it with Sideloadly and that worked with the MDC Bypass 3 App Limit tool but for whatever reason it's saying there's more updates. I ended up just skipping the update, so it doesn't show up and then I'll just check every few weeks if there's an update. 

> Then when I try to update, that has issues leading to the app crashing.

What do you mean by update? Do you mean the way that I first described by just overwriting the installed version? If so, that's the same issue I'm getting. If you mean pressing the update button in the popup, then I'm unsure. I ran out of App IDs for the other Apple ID I'm using.

**Comment by shanegillio** [comment] 2023-02-08 20:25
OK, thanks so much for the explanation - it's helpful to see the full context. You can in fact sideload IPA's with AltServer, but it's intentionally a hidden feature since it causes issues like this. 

I did have an update attempt where I did the overwriting method as you said, and the new version would always crash on launch. But if I just installed the latest GitHub release it would work and I just ignored the update request. 

It's possible this has something to do with the App Extensions installed or that it is losing connection with AltServer and just hanging without throwing a timeout error. Based on my own testing, seems you can install the latest IPA just fine and then ignore the update notification.Did you select "Keep App Extensions" or remove?

**Comment by gmanc2** [comment] 2023-02-08 20:34
> OK, thanks so much for the explanation - it's helpful to see the full context. You can in fact sideload IPA's with AltServer, but it's intentionally a hidden feature since it causes issues like this.
> 
> I did have an update attempt where I did the overwriting method as you said, and the new version would always crash on launch. But if I just installed the latest GitHub release it would work and I just ignored the update request.
> 
> It's possible this has something to do with the App Extensions installed or that it is losing connection with AltServer and just hanging without throwing a timeout error. Based on my own testing, seems you can install the latest IPA just fine and then ignore the update notification.Did you select "Keep App Extensions" or remove?

I just attempted to download the most recent version [v18.01.6-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.01.6-2.3.1) and the same issue occurred where it hangs. I currently have an older version. I connect my phone to the computer, open alt server, download the IPA on chrome on my phone. Open in Altstore, "Keep App Extensions". After that the loading bar gets to about the 3/4 mark and hangs for hours. I've waited a long time before an it just keeps spinning. As stated earlier, I can not delete the uYou+ app without out having to go through an extremely tedious login process that does not always work. There are no error logs, also the reason it keeps saying there is an update is because this is a modified version of the original uYou app which gets updated more frequently than the uYou+ app. This leads to uYou(The base app) to believe it needs updated even when it does not. Since its a modified version it can not update itself as designed by the original developer. Is there any way currently to make it work(secret settings) or be able to provide some log to help you debug?

**Comment by shanegillio** [comment] 2023-02-08 21:57
So what may be happening, at least from how my testing has gone, is AltServer is waiting for some response and then it just hangs. There won't be any error log unfortunately because it essentially amount to being a timeout error. 

I'm trying to narrow down what kind of response AltServer is looking for, and my guess is it may be due to this version of the app having something different from the old version (such as app extensions) which would maybe cause it to not complete the update. 

I'm going to do so more testing soon - I want to see if I can even update the same exact version over itself. If that works, then it would seem something about the difference between the old and new versions is keeping it from completing. More to come!

**Comment by shanegillio** [comment] 2023-02-08 21:59
To be clear though, you are using uYou+ and trying to update to a new version of uYou+.

You're not trying to update from the "base app" to the + version, correct?

**Comment by jasonhe54** [comment] 2023-02-09 00:09
> I did have an update attempt where I did the overwriting method as you said, and the new version would always crash on launch.

Wait, so overwriting it would work? That's beyond where I got. For me, it's the overwriting process that hangs. Perhaps you could try using the same version that I'm using to see if there's any changes? 
Installed Version: https://github.com/qnblackcat/uYouPlus/releases/tag/v17.43.1-2.1
Version I'm trying to update to: https://github.com/qnblackcat/uYouPlus/releases/tag/v18.01.6-2.3.1

>It's possible this has something to do with the App Extensions installed...Did you select "Keep App Extensions" or remove?

I usually just remove app extensions because I never really bothered figuring out what it did myself and it took up more app IDs. The app works without it, so I just remove them. In both cases, I opted to remove App Exts. I'm sure you can delete the old version and then install the new version fine (it does just take a while, but it eventually succeeds). Not sure if the same issue happens when deleting and install the new version, haven't done that in a while. 

Quoting @gmanc2's replies from now:
>After that the loading bar gets to about the 3/4 mark and hangs for hours.

I haven't left it for hours, but for me it makes it to basically the end, but then the bar just stops moving. Not sure what percent approx. 

>P.S Im on the most recent beta of AltStore with an apple developer account.

if it helps, I'm on AltStore 1.6 with a free Apple Developer Account

> having something different from the old version (such as app extensions) 

Maybe that's possible but then it wouldn't make sense why removing App Extensions in both installs wouldn't fix it.

> To be clear though, you are using uYou+ and trying to update to a new version of uYou+.
You're not trying to update from the "base app" to the + version, correct?

That is correct. Don't think there's a way to update the "base app" (uYou) without manually decrypting YouTube and then injecting the uYou deb into it with Sideloadly or something. Haven't tried that and have no clue how to.

**Comment by gmanc2** [comment] 2023-02-20 18:28
> To be clear though, you are using uYou+ and trying to update to a new version of uYou+.
> 
> You're not trying to update from the "base app" to the + version, correct?

Yes that's correct sorry for the late reply.

**Comment by gmanc2** [comment] 2023-02-25 03:50
@shanegillio @rileytestut Do you have an update on this? No rush.

**Comment by shanegillio** [comment] 2023-02-27 22:19
We will be taking a look at this in the next batch of betas, so hard to say when this will be resolved exactly. I've put this as a priority bug to look at when we next get to taking care of bug reports. Remind me to check back here if it goes for awhile. Sorry for any inconvenience.

**Comment by gmanc2** [comment] 2023-02-27 22:23
Update: On the Beta version of the app, it still hangs I tried reinstalling AltStore through AltServer and it still didn't work on the beta. However, I then built up the courage to delete the uYou+ app since my version was having issues and tried the beta version again "knowing it would work". However, it didn't it hung again for 30 minutes and then I closed AltStore. I then deleted the Beta version and installed the regular AltStore, and it installed **AND KEPT ME LOGGED IN!**. I don't know if it will always keep me logged in (uYou+ that is), but it worked this time. As a reminder, **I still had to delete the uYou+ app** and remove the AltStore beta for it to work which was the whole problem, to begin with as apparently "Sometimes" (It was said it always does it but that's proven to be untrue) when you delete uYou+ it logs you out and prevents login again without a giant pain of a workaround. This is good news that at least its still able to be installed if you remove the uYou+ app but it would be much better if you could just load the new version in AltStore while the previous one is still installed.

**Comment by theLastOfCats** [comment] 2023-03-02 17:19
I got strange problem with uYou+ installed from ipa
It's not visible in apps section, but I can see it in appids
Fresh installed AltStore, ipad mini 6, iPadOS 16.3.1

![Screenshot%202023-03-02%20at%2020 15 10](https://user-images.githubusercontent.com/3687591/222503469-39a663b6-51bc-47d0-bd63-120d032ba2ef.png)
![Screenshot%202023-03-02%20at%2020 15 23](https://user-images.githubusercontent.com/3687591/222503477-8b9edffe-d3d8-437c-8798-0da71620dfce.png)

**Comment by gmanc2** [comment] 2023-07-19 17:55
> Hi All! We released a beta version that was directed at apps hanging on install - have you tried @gmanc2 ?

Hey, I have not tried it yet I'll let you know on the next update.

**Closed** 2023-09-21 19:05 UTC
Labels: bug
