### ISSUE TITLE
MacOS 14 - Unable to connect to Mail Plug-in

### ISSUE THREAD

**Issue by L0rdLogan** [altstoreio/AltStore#1274] opened 2023-08-19 17:43 UTC
In MacOS 14, they removed the Mail Plugin's completely, needs to now be a mail extension 

![image](https://github.com/altstoreio/AltStore/assets/5092548/dc4989ed-3d6c-40d4-b041-0cc575e95f83)

**Comment by Avakining** [comment] 2023-08-20 07:53
Duplicate of #1252

**Closed** 2023-08-21 14:54 UTC
